# List of participants

* Acevedo Limón, Lucía (lucia.acevedo@uca.es) *University of Cádiz, Spain*
* Acosta Rojas, Diana Carolina (diana.acosta@senckenberg.de) *Senckenberg Biodiversity and Climate Research Center, Germany*
* Aghai, Matthew (matthew@droneseed.co) *DroneSeed Co., United States*
* Albani Rocchetti, Giulia (giulia.albanirocchetti@uniroma3.it) *Roma Tre University, Italy*
* Arend da Silva, Isis (i.arenddasilva@uqconnect.edu.au) *University of Queensland, Australia*
* Arnberg, Mie (mie.p.arnberg@nord.no) *Nord University, Norway*
* Bacchetta, Gianluigi (bacchet@unica.it) *University of Cagliari, Italy*
* Bracho Estévanez, Claudio Açaí (claudio.bracho@uca.es) *University of Cádiz, Spain*
* Bruno, Fogliani (bruno.fogliani@unc.nc) *University of New Caledonia, New Caledonia*
* Bucharova, Anna (anna.lampei-bucharova@uni-marburg.de) *University of Marburg, Germany*
* Carlón Ruiz, Luis (lcarlon77@gmail.com) *Biosfera S.L., Spain*
* Caro Beveridge, Fernanda (fernanda.carobeveridge@uq.net.au) *University of Queensland, Australia*
* Carta, Angelino (angelino.carta@unipi.it) *University of Pisa, Italy*
* Castillo-Lorenzo, Elena (e.castillolorenzo@kew.org) *Royal Botanic Gardens, Kew, United Kingdom*
* Chandler, Jake Owen (jake.chandler@rhul.ac.uk) *Royal Holloway University of London, United Kingdom*
* Chen, Si-Chong (chensichong0528@gmail.com) *Royal Botanic Gardens, Kew, China*
* Chmielarz, Paweł (pach@man.poznan.pl) *Institute of Dendrology, Polish Academy of Sciences, Poland*
* Copete Carreño, María Elena (mariaelena.copete@uclm.es) *University of Castilla-La Mancha, Spain*
* Copete Carreño, Miguel Ángel (miguel.copete@uclm.es) *University of Castilla-La Mancha, Spain*
* Cruz Tejada, Diana María (diana.cruztejada@phd.unipi.it) *University of Pisa, Italy*
* Cuena-Lombraña, Alba (albacuena@gmail.com) *University of Cagliari, Italy*
* Daskalakou, Evangelia (edaskalakou@gmail.com) *Institute of Mediterranean Forest Ecosystems, Greece*
* Davies, Rachael (rachael.davies@kew.org) *Royal Botanic Gardens, Kew, United Kingdom*
* Dayrell de Lima Campos, Roberta (Roberta.Dayrell@biologie.uni-regensburg.de) *University of Regensburg, Germany*
* Del Vecchio, Silvia (silvia.delvecchio@unive.it) *Ca' Foscari University of Venice, Italy*
* Di Cecco, Valter (valter.dicecco@parcomajella.it) *Maiella National Park, Italy*
* Di Martino, Luciano (luciano.dimartino@parcomaiella.it) *Maiella National Park, Italy*
* Di Musciano, Michele (michele.dimusciano@univaq.it) *University of L'Aquila, Italy*
* Dickie, John (j.dickie@kew.org) *Royal Botanic Gardens, Kew, United Kingdom*
* Espinosa del Alba, Clara (espinosaclara@uniovi.es) *University of Oviedo, Spain*
* Eycott, Amy Elizabeth (amy.eycott@nord.no) *Nord University, Norway*
* Fatelnig, Lena (lena.fatelnig@rhul.ac.uk) *Royal Holloway University of London, United Kingdom*
* Fernández-Pascual, Eduardo (fernandezpeduardo@uniovi.es) *University of Oviedo, Spain*
* Fidelis, Alessandra (alessandra.fidelis@unesp.br) *São Paulo State University, Brazil*
* Fois, Mauro (foisma@yahoo.it) *University of Cagliari, Italy*
* Fuzessy, Lisieux (lfuzessy@gmail.com) *Center for Ecological Research and Forestry Applications, Spain*
* Gálvez Ramírez, Cándido (candido@semillassilvestres.com) *Semillas Silvestres S.L., Spain*
* Gamarra, Roberto (roberto.gamarra@uam.es) *Autonomous University of Madrid, Spain*
* García, Daniel (danielgarcia@uniovi.es) *University of Oviedo, Spain*
* Gasparini Martins, Raquel (rg.martins@unesp.br) *São Paulo State University, Brazil*
* González García, Víctor (victor_pola97@hotmail.com) *University of Oviedo, Spain*
* Greta, Ivesdal (thomas.roman@ife-edu.eu) *University of Denver, United States*
* Guja, Lydia (Lydia.Guja@environment.gov.au) *Australian National Botanic Gardens, Australia*
* Gunadasa, Nethani Hansana (nethanihansana@gmail.com) *University of Peradeniya, Sri Lanka*
* Hay, Fiona (fiona.hay@agro.au.dk) *University of Aarhus, Denmark*
* Hernández-Mendoza, Vanessa (bea.custodio13@gmail.com) *Yucatán Scientific Research Center, Mexico*
* Herranz Sanz, José María (jose.herranz@uclm.es) *University of Castilla-La Mancha, Spain*
* Hoyle, Gemma (Gemma.Hoyle@environment.gov.au) *Australian National Botanic Gardens, Australia*
* Isla, Jorge (jorge.isla@ebd.csic.es) **Doñana Biological Station, CSIC, Spain*
* Jiménez-Alfaro, Borja (jimenezalfaro@uniovi.es) *University of Oviedo, Spain*
* Khajeh-Hosseini, Mohammad (agr844@gmail.com) *Ferdowsi University of Mashhad, Iran*
* Kildisheva, Olga (olga.kildisheva@gmail.com) *The Nature Conservancy, United States*
* Kourmpetli, Sofia (s.kourmpetli@cranfield.ac.uk) *Cranfield University, United Kingdom*
* Lázaro-Lobo, Adrián (adrianlalobo@gmail.com) *University of Alcalá, Spain*
* Lepková, Barbora (barbora.lepkova@natur.cuni.cz) *Charles University, Czech Republic*
* Leubner-Metzger, Gerhard (Gerhard.Leubner@rhul.ac.uk) *Royal Holloway University of London, United Kingdom*
* López Almeida, Gloria (calidad@semillassilvestres.com) *Semillas Silvestres S.L., Spain*
* López Camacho, Adolfo (administracion@semillassilvestres.com) *Semillas Silvestres S.L., Spain*
* Lourenço Zirondi, Heloiza (heloiza.l.zirondi@unesp.br) *São Paulo State University, Brazil*
* Luna, Belén (Belen.Luna@uclm.es) *University of Castilla-La Mancha, Spain*
* Magrini, Sara (magrini@unitus.it) *Tuscia University, Italy*
* Malavert, Cristian (malavert@agro.uba.ar) *University of Buenos Aires, Argentina*
* Mašková, Tereza (terezapechova@gmail.com) *University of Regensburg, Germany*
* McInnes, Sarah Jane (s.mcinnes@student.unsw.edu.au) *University of New South Wales, Australia*
* Medrán Viñas, Ángela (angela@semillassilvestres.com) *Semillas Silvestres S.L., Spain*
* Mondoni, Andrea (andrea.mondoni@unipv.it) *University of Pavia, Italy*
* Muñoz Gallego, Raquel (rmunoz@imedea.uib-csic.es) *Mediterranean Institute of Advanced Studies, CSIC-UIB, Spain*
* Muñoz Rojas, Miriam (mmunnoz1@us.es) *University of Seville, Spain*
* Muthuthanthirige, Deshika (deshikalm@gmail.com) *University of Peradeniya, Sri Lanka*
* Oikonomidis, Spyridon (soikonomidis@biol.uoa.gr) *National and Kapodistrian University of Athens, Greece*
* Ooi, Mark (mark.ooi@unsw.edu.au) *University of New South Wales, Australia*
* Ordóñez Parra, Carlos Andrés (carlos.ordonez.parra@gmail.com) *Federal University of Minas Gerais, Brazil*
* Ortúñez, Emma (emma.ortunez@uam.es) *Autonomous University of Madrid, Spain*
* Papouskova, Ludmila (papouskova@vurv.cz) *Crop Research Institute, Czech Republic*
* Paroissien, Ruby (r.paroissien@unsw.edu.au) *University of New South Wales, Australia*
* Pawłowski, Tomasz Andrzej (tapawlow@man.poznan.pl) *Institute of Dendrology, Polish Academy of Sciences, Poland*
* Pérez, Héctor (heperez@ufl.edu) *University of Florida, United States*
* Pérez Suárez, Marta (Marta.Perez@rhul.ac.uk) *Royal Holloway University of London, United Kingdom*
* Phartyal, Shyam S. (shyamphartyal@gmail.com) *Nalanda University, India*
* Pinzani, Lorenzo (lorenzo.pinzani@phd.unipi.it) *University of Pisa, Italy*
* Piñas Bonilla, Paula (paula.pinas@uclm.es) *University of Castilla-La Mancha, Spain*
* Ramírez Chueca, Esteban (esteban.ramirez@uam.es) *Autonomous University of Madrid, Spain*
* Rosbakh, Sergey (sergey.rosbakh@ur.de) *University of Regensburg, Germany*
* Saatkamp, Arne (arne.saatkamp@imbe.fr) *Aix Marseille University IMBE, France*
* Serra-Díaz, Josep M. (pep.serradiaz@agroparistech.fr) *AgroParisTech, France*
* Silveira, Fernando A.O. (faosilveira@gmail.com) *Federal University of Minas Gerais, Brazil*
* Tangney, Ryan (R.tangney@unsw.edu.au) *University of New South Wales, Australia*
* Tavsanoglu, Cagatay (ctavsanoglu@gmail.com) *Hacettepe Universituy, Turkey*
* Trotta, Giacomo (giacomo.trotta@phd.units.it) *University of Trieste, Italy*
* Valdelvira Medina, Guillermo (guill.v.m.1998@gmail.com) *Autonomous University of Madrid, Spain*
* Vandelook, Filip (filip.vandelook@botanicgardenmeise.be) *Meise Botanic Garden, Belgium*
* Vázquez-Ramírez, Jerónimo (jvazquezramirez@deakin.edu.au) *Deakin University, Australia*
* Venceslai, Nahema (nahema.venceslai.2020@live.rhul.ac.uk) *Royal Holloway University of London, United Kingdom*
* Villa, Sara (sara.villa1@unimi.it) *University of Milan, Italy*
* Vuerich, Marco (marco.vuerich@uniud.it) *University of Udine, Italy*
* Wawrzyniak, Mikołaj (mikwaw@man.poznan.pl) *Institute of Dendrology, Polish Academy of Sciences, Poland*
* White, Fiona (fionajane.white01@universitadipavia.it) *University of Pavia, Italy*